package com.ml

/**
  * Created by wangqi08 on 1/7/2016.
  */
object CategoryUtils {
  def categoryToInt(s: String): Int = {
    lazy val list = List("INSB", "PWASH", "NC", "IMF", "SKIN", "PHS", "FB", "DCONF", "BABYNUTRFOOD", "TP", "FACIALMASK", "DIAP", "VITAMINS", "MILK", "BIS", "BABYP", "SP", "EDOIL", "SHAM", "QSOUP", "CMSNACK", "BFOOD", "TB", "BABYW", "LIPPALM", "CALCIUM", "FACIA", "INSR", "CHEESE", "CONF", "TPOWD", "LLP", "DWL", "SKIN/TONER", "HONEY", "LAUND", "FT", "SUGAR", "SOYSAUCE", "PTBH", "CPASTRY", "SHAM/HAIR", "CSD", "BODYTLPW", "TEA", "CF", "CHISPIRITS", "YD", "BBCREAM", "JUICE", "AD", "NOODLE", "COFF", "BP", "CPS", "HAIR", "FROHOTPOT", "CERE", "DEODORANT", "SNACK", "BANDEDPACK", "NUTS", "SEALBC", "MOUTHWASH", "SKIN/FACIA/TONER", "TONER", "INSE", "LIQM", "JELLY", "TP/TB", "FT/FB", "HGLOVES", "CONDOM", "HC", "PDF", "CALCIUM/PHS", "VINEG", "ATD", "BREAD", "FD", "SHAVERS", "HERBALTEA", "STARCH", "NOOD", "SD", "DPASTA", "HOUS", "DF", "PTBR", "WATER", "AIR", "CORD", "FABRICS", "PWASH/SKIN", "LS", "RDT", "SHOE", "RICE", "CDRYFRUIT", "MOIS", "HAIDS", "PWASH/SHAM", "ICECR", "SKIN/FACIA/TONER/FACIALMASK", "LGELS", "FWINE", "PWASH/SHAM/SKIN/BABYP", "HAIRS", "FACIALT", "DIMSUM", "PWASH/SHAM/SKIN", "SKIN/FACIALMASK", "PWASH/SHAM/HAIR", "EGG", "CPOWDER", "SKIN/FACIA", "RPM", "SMP", "CAKE", "PFLOUR", "PWASH/BABYP/INSB", "SPICES", "PLASTICB", "RTDSM", "PWASH/SHAM/SKIN/FACIA/TONER", "RTDC", "GUM")
    val map = list.zipWithIndex.toMap
    map.getOrElse(s, 127)
  }

}
